// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7ENCZaq4CiKeX8wDogY-gr67HTuK6ZUw',
    appId: '1:375229188872:web:20a184d868b165c693babd',
    messagingSenderId: '375229188872',
    projectId: 'task-5-fa2fb',
    authDomain: 'task-5-fa2fb.firebaseapp.com',
    storageBucket: 'task-5-fa2fb.appspot.com',
    measurementId: 'G-Q59LWHZDE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgk-KhbAYdw0vc5kAvcsywk5QNr25dL5E',
    appId: '1:375229188872:android:b0aef383f97ac18293babd',
    messagingSenderId: '375229188872',
    projectId: 'task-5-fa2fb',
    storageBucket: 'task-5-fa2fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj4oPhU81DtDmeQj4pCADawyW69wpp4I4',
    appId: '1:375229188872:ios:6ca3c968ffbba0b793babd',
    messagingSenderId: '375229188872',
    projectId: 'task-5-fa2fb',
    storageBucket: 'task-5-fa2fb.appspot.com',
    iosClientId: '375229188872-evqdefu6j4fcv9uq57ojtbee3tgj2uar.apps.googleusercontent.com',
    iosBundleId: 'com.example.task3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj4oPhU81DtDmeQj4pCADawyW69wpp4I4',
    appId: '1:375229188872:ios:6ca3c968ffbba0b793babd',
    messagingSenderId: '375229188872',
    projectId: 'task-5-fa2fb',
    storageBucket: 'task-5-fa2fb.appspot.com',
    iosClientId: '375229188872-evqdefu6j4fcv9uq57ojtbee3tgj2uar.apps.googleusercontent.com',
    iosBundleId: 'com.example.task3',
  );
}
